<cfcomponent output="no">
	<cfoutput>
	<cffunction name="index" localmode="modern" access="remote" output="yes" returntype="any">
    	<cfargument name="id" type="string" required="no" default="0">
    	<cfargument name="arg2" type="string" required="no" default="">
    	<cfargument name="arg3" type="string" required="no" default="">
    	<cfargument name="arg4" type="string" required="no" default="">
    	<cfargument name="arg5" type="string" required="no" default="">
        <cfscript>
		application.zcore.template.settag("title","Model View Controller (MVC) Example");
		application.zcore.template.settag("pagetitle","Model View Controller (MVC) Example");
		</cfscript>
        <p>This page was generated by an MVC controller with our custom framework.</p>
        <h2>Arguments</h2>
        <cfdump var="#arguments#">
        <br style="clear:both;" />
        zcorerootmapping.mvc.controller.test.cfc -> index() called.
        
	</cffunction>
    
	<cffunction name="edit" localmode="modern" access="remote" output="yes" returntype="any">
    	<cfargument name="id" type="string" required="no" default="0">
		<cfscript>
		var local=structnew();
		// arguments._zExtraArguments is also available if more fields were in the url then there were arguments for.
		
		</cfscript>
        mvc.controller.Test.cfc -> edit() called.
	</cffunction>
    </cfoutput>
</cfcomponent>